baseURL = "https://www.ipvtechresearch.org"
languageCode = "en-us"
title = "IPV Tech Research"
theme = "hugo-material-blog"

[params]
description = "Improving digital safety, security, and privacy for survivors of intimate partner violence"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[[menu.main]]
name = "About"
weight = 1
identifier = "about-1"
url = "/"

[[menu.main]]
name = "People"
weight = 2
identifier = "people-1"
url = "/people/"

[[menu.main]]
name = "Publications"
weight = 3
identifier = "publications-1"
url = "/publications/"

[[menu.main]]
name = "Partners"
weight = 4
identifier = "partners-1"
url = "/partners/"

[[menu.main]]
name = "Funding"
weight = 5
identifier = "funding-1"
url = "/funding/"

[[menu.main]]
name = "Resources"
weight = 6
identifier = "resources-1"
url = "/resources/"


#[[menu.main]]
#name = "Guides"
#weight = 7
#identifier = "guides-1"
#url = "/guides/"
