baseURL = "https://stopipv.github.io/"
languageCode = "en-us"
title = "Technology and Intimate Partner Violence (IPV)"
theme = "amp"

[params]
description = "Improving digital safety, security, and privacy for survivors of intimate partner violence"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true


[[menu.main]]
name = "people"
weight = 2
identifier = "people-1"
url = "/post/people/"

[[menu.main]]
name = "publications"
weight = 3
identifier = "publications-1"
url = "/post/publications/"

[[menu.main]]
name = "community partners"
weight = 4
identifier = "community-partners-1"
url = "/post/community-partners/"

[[menu.main]]
name = "funding"
weight = 5
identifier = "funding-1"
url = "/post/funding/"
